version: '3.6'
services:  
  mysql:
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=my_password